name: Publishes a new package of Zebble or any of its CLIs to the nuget.org
on:
  push:
    branches: [ main ]
jobs:
  build_zebble:
    strategy:
      matrix:
        configuration: [ Release ]
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Install MAUI
      run: dotnet workload install ios android maui --source https://aka.ms/dotnet8/nuget/index.json --source https://api.nuget.org/v3/index.json

    - name: Install Zebble's CLI tools
      run: dotnet tool install --global zebble-build

    - name: Publish a new Zebble package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Zebble

  build_zebble_build:
    strategy:
      matrix:
        configuration: [ Release ]
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Install Zebble's CLI tools
      run: dotnet tool install --global zebble-build

    - name: Publish a new Zebble.Build package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Zebble.Build

  build_zebble_compile_zbl:
    strategy:
      matrix:
        configuration: [ Release ]
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Install Zebble's CLI tools
      run: dotnet tool install --global zebble-build

    - name: Publish a new Zebble.CompileZbl package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Zebble.CompileZbl
      
  build_zebble_css:
    strategy:
      matrix:
        configuration: [ Release ]
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Install Zebble's CLI tools
      run: dotnet tool install --global zebble-build

    - name: Publish a new Zebble.Css package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Zebble.Css
      
  build_zebble_format_zbl:
    strategy:
      matrix:
        configuration: [ Release ]
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Install Zebble's CLI tools
      run: dotnet tool install --global zebble-build

    - name: Publish a new Zebble.FormatZbl package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Zebble.FormatZbl
      
  build_zebble_image:
    strategy:
      matrix:
        configuration: [ Release ]
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Install Zebble's CLI tools
      run: dotnet tool install --global zebble-build

    - name: Publish a new Zebble.Image package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Zebble.Image

  build_zebble_schema:
    strategy:
      matrix:
        configuration: [ Release ]
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Install Zebble's CLI tools
      run: dotnet tool install --global zebble-build

    - name: Publish a new Zebble.Schema package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Zebble.Schema